module Flag.Render.Prov
    ( generateProvXml
    ) where

import Data.Char (toLower)
import Data.List (nub, isPrefixOf)

import Flag.Source (Source(..), Entity(..), Agent(..), SourcedElement)

-- | Generate a W3C PROV-XML document for a flag's provenance.
generateProvXml :: String -> String -> [SourcedElement] -> String
generateProvXml isoCode flagName' sources =
  unlines
    [ "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
    , "<prov:document xmlns:prov=\"http://www.w3.org/ns/prov#\""
    , "               xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\""
    , "               xmlns:cf=\"http://constructibleflags.com/ns#\">"
    , ""
    , "  <!-- The constructed flag -->"
    , "  <prov:entity prov:id=\"cf:" ++ isoLower ++ "_flag\">"
    , "    <prov:label>" ++ escXml flagName' ++ "</prov:label>"
    , "    <prov:type xsd:type=\"xsd:QName\">cf:Flag</prov:type>"
    , "  </prov:entity>"
    , ""
    , "  <!-- The construction activity -->"
    , "  <prov:activity prov:id=\"cf:" ++ isoLower ++ "_construction\">"
    , "    <prov:label>Construction of " ++ escXml flagName' ++ " flag</prov:label>"
    , "    <prov:type xsd:type=\"xsd:QName\">cf:Construction</prov:type>"
    , "  </prov:activity>"
    , ""
    , "  <!-- The flag was generated by the construction activity -->"
    , "  <prov:wasGeneratedBy>"
    , "    <prov:entity prov:ref=\"cf:" ++ isoLower ++ "_flag\" />"
    , "    <prov:activity prov:ref=\"cf:" ++ isoLower ++ "_construction\" />"
    , "  </prov:wasGeneratedBy>"
    , ""
    , "  <!-- Editor agent -->"
    , "  <prov:agent prov:id=\"cf:editor\">"
    , "    <prov:label>Xavier Shay</prov:label>"
    , "    <prov:type xsd:type=\"xsd:QName\">prov:Person</prov:type>"
    , "  </prov:agent>"
    , if hasTranslations then unlines
        [ ""
        , "  <!-- Google Translate (corroborating tool for translations) -->"
        , "  <prov:agent prov:id=\"cf:google_translate\">"
        , "    <prov:label>Google Translate</prov:label>"
        , "    <prov:type xsd:type=\"xsd:QName\">prov:SoftwareAgent</prov:type>"
        , "  </prov:agent>"
        ] else ""
    , ""
    , "  <!-- The construction was associated with the editor -->"
    , "  <prov:wasAssociatedWith>"
    , "    <prov:activity prov:ref=\"cf:" ++ isoLower ++ "_construction\" />"
    , "    <prov:agent prov:ref=\"cf:editor\" />"
    , "  </prov:wasAssociatedWith>"
    , ""
    , agentDeclarations
    , entityDeclarations
    , pantoneSamplingDeclarations
    , sourceValueDeclarations
    , usedDeclarations
    , relationshipDeclarations
    , "</prov:document>"
    ]
  where
    isoLower = map toLower isoCode

    hasTranslations :: Bool
    hasTranslations = any (\e -> entityTranslated e /= Nothing) allEntities

    -- Collect all unique agents from sources
    allAgents :: [Agent]
    allAgents = nub [ a | (_, src) <- sources, a <- sourceAgents src ]

    sourceAgents :: Source -> [Agent]
    sourceAgents (SourceReference e) = entityAgents e
    sourceAgents (SourceImpliedReference e) = entityAgents e
    sourceAgents (SourceUnsightedReference e refs) = entityAgents e ++ concatMap entityAgents refs
    sourceAgents (SourceEditorial refs) = concatMap entityAgents refs

    entityAgents :: Entity -> [Agent]
    entityAgents e = case entityAgent e of
      Just a  -> [a]
      Nothing -> []

    -- Collect all unique entities from sources
    allEntities :: [Entity]
    allEntities = nub [ e | (_, src) <- sources, e <- sourceEntities src ]

    sourceEntities :: Source -> [Entity]
    sourceEntities (SourceReference e) = [e]
    sourceEntities (SourceImpliedReference e) = [e]
    sourceEntities (SourceUnsightedReference e refs) = e : refs
    sourceEntities (SourceEditorial refs) = refs

    -- Generate agent declarations
    agentDeclarations :: String
    agentDeclarations = unlines $
      [ "  <!-- Source agents -->" | not (null allAgents) ] ++
      concatMap agentDecl allAgents

    agentDecl :: Agent -> [String]
    agentDecl a =
      [ "  <prov:agent prov:id=\"cf:" ++ escId (agentId a) ++ "\">"
      , "    <prov:label>" ++ escXml (agentName a) ++ "</prov:label>"
      , "    <prov:type xsd:type=\"xsd:QName\">prov:Organization</prov:type>"
      , "  </prov:agent>"
      ]

    -- Generate entity declarations for source documents
    entityDeclarations :: String
    entityDeclarations = unlines $
      [ "  <!-- Source documents -->" | not (null allEntities) ] ++
      concatMap entityDecl allEntities

    entityDecl :: Entity -> [String]
    entityDecl e =
      [ "  <prov:entity prov:id=\"cf:" ++ entityIdStr e ++ "\">"
      , "    <prov:label>" ++ escXml (entityTitle e) ++ "</prov:label>"
      , "    <prov:type xsd:type=\"xsd:QName\">cf:SourceDocument</prov:type>"
      ] ++
      [ "    <prov:location>" ++ escXml (entityUrl e) ++ "</prov:location>"
      | not (null (entityUrl e)) ] ++
      [ "  </prov:entity>"
      ] ++
      -- wasAttributedTo for entity's agent
      maybe []
        (\a ->
          [ "  <prov:wasAttributedTo>"
          , "    <prov:entity prov:ref=\"cf:" ++ entityIdStr e ++ "\" />"
          , "    <prov:agent prov:ref=\"cf:" ++ escId (agentId a) ++ "\" />"
          , "  </prov:wasAttributedTo>"
          ])
        (entityAgent e) ++
      -- Screenshot as a separate entity generated by viewing the original
      maybe []
        (\(date, path) ->
          let screenId = screenshotIdStr e
              viewId = "view_" ++ entityIdStr e
          in
          [ "  <prov:entity prov:id=\"cf:" ++ screenId ++ "\">"
          , "    <prov:label>Screenshot of " ++ escXml (entityTitle e) ++ "</prov:label>"
          , "    <prov:type xsd:type=\"xsd:QName\">cf:Screenshot</prov:type>"
          , "    <prov:location>" ++ escXml path ++ "</prov:location>"
          , "  </prov:entity>"
          , "  <prov:activity prov:id=\"cf:" ++ viewId ++ "\">"
          , "    <prov:label>View " ++ escXml (entityTitle e) ++ "</prov:label>"
          , "    <prov:type xsd:type=\"xsd:QName\">cf:View</prov:type>"
          , "    <prov:startTime>" ++ escXml date ++ "T00:00:00</prov:startTime>"
          , "    <prov:endTime>" ++ escXml date ++ "T00:00:00</prov:endTime>"
          , "  </prov:activity>"
          , "  <prov:wasGeneratedBy>"
          , "    <prov:entity prov:ref=\"cf:" ++ screenId ++ "\" />"
          , "    <prov:activity prov:ref=\"cf:" ++ viewId ++ "\" />"
          , "  </prov:wasGeneratedBy>"
          , "  <prov:used>"
          , "    <prov:activity prov:ref=\"cf:" ++ viewId ++ "\" />"
          , "    <prov:entity prov:ref=\"cf:" ++ entityIdStr e ++ "\" />"
          , "  </prov:used>"
          , "  <prov:wasAssociatedWith>"
          , "    <prov:activity prov:ref=\"cf:" ++ viewId ++ "\" />"
          , "    <prov:agent prov:ref=\"cf:editor\" />"
          , "  </prov:wasAssociatedWith>"
          , "  <prov:wasDerivedFrom>"
          , "    <prov:generatedEntity prov:ref=\"cf:" ++ screenId ++ "\" />"
          , "    <prov:usedEntity prov:ref=\"cf:" ++ entityIdStr e ++ "\" />"
          , "  </prov:wasDerivedFrom>"
          ])
        (entityScreenshot e) ++
      -- Translation as a separate entity generated by translating the source
      maybe []
        (\date ->
          let transId = translationIdStr e
              translateActId = "translate_" ++ entityIdStr e
              -- Translation derives from screenshot if present, otherwise from entity directly
              sourceId = case entityScreenshot e of
                Just _  -> screenshotIdStr e
                Nothing -> entityIdStr e
          in
          [ "  <prov:entity prov:id=\"cf:" ++ transId ++ "\">"
          , "    <prov:label>Translation of " ++ escXml (entityTitle e) ++ "</prov:label>"
          , "    <prov:type xsd:type=\"xsd:QName\">cf:Translation</prov:type>"
          , "  </prov:entity>"
          , "  <prov:activity prov:id=\"cf:" ++ translateActId ++ "\">"
          , "    <prov:label>Translate " ++ escXml (entityTitle e) ++ "</prov:label>"
          , "    <prov:type xsd:type=\"xsd:QName\">cf:Translation</prov:type>"
          , "    <prov:startTime>" ++ escXml date ++ "T00:00:00</prov:startTime>"
          , "    <prov:endTime>" ++ escXml date ++ "T00:00:00</prov:endTime>"
          , "  </prov:activity>"
          , "  <prov:wasGeneratedBy>"
          , "    <prov:entity prov:ref=\"cf:" ++ transId ++ "\" />"
          , "    <prov:activity prov:ref=\"cf:" ++ translateActId ++ "\" />"
          , "  </prov:wasGeneratedBy>"
          , "  <prov:used>"
          , "    <prov:activity prov:ref=\"cf:" ++ translateActId ++ "\" />"
          , "    <prov:entity prov:ref=\"cf:" ++ sourceId ++ "\" />"
          , "  </prov:used>"
          , "  <prov:wasAssociatedWith>"
          , "    <prov:activity prov:ref=\"cf:" ++ translateActId ++ "\" />"
          , "    <prov:agent prov:ref=\"cf:editor\" />"
          , "  </prov:wasAssociatedWith>"
          , "  <prov:wasAssociatedWith>"
          , "    <prov:activity prov:ref=\"cf:" ++ translateActId ++ "\" />"
          , "    <prov:agent prov:ref=\"cf:google_translate\" />"
          , "  </prov:wasAssociatedWith>"
          , "  <prov:wasDerivedFrom>"
          , "    <prov:generatedEntity prov:ref=\"cf:" ++ transId ++ "\" />"
          , "    <prov:usedEntity prov:ref=\"cf:" ++ sourceId ++ "\" />"
          , "  </prov:wasDerivedFrom>"
          ])
        (entityTranslated e)

    -- Generate entity declarations for sourced values (e.g. "Blue", "Red")
    sourceValueDeclarations :: String
    sourceValueDeclarations = unlines $
      [ "  <!-- Sourced values -->" | not (null sources) ] ++
      concatMap (\(name, _) ->
        [ "  <prov:entity prov:id=\"cf:" ++ isoLower ++ "_" ++ escId name ++ "\">"
        , "    <prov:label>" ++ escXml name ++ "</prov:label>"
        , "    <prov:type xsd:type=\"xsd:QName\">cf:SourcedValue</prov:type>"
        , "  </prov:entity>"
        ]) sources

    -- The construction activity used each sourced value
    usedDeclarations :: String
    usedDeclarations = unlines $
      [ "  <!-- Construction used these sourced values -->" | not (null sources) ] ++
      concatMap (\(name, _) ->
        [ "  <prov:used>"
        , "    <prov:activity prov:ref=\"cf:" ++ isoLower ++ "_construction\" />"
        , "    <prov:entity prov:ref=\"cf:" ++ isoLower ++ "_" ++ escId name ++ "\" />"
        , "  </prov:used>"
        ]) sources

    -- Generate relationship declarations for each sourced value
    relationshipDeclarations :: String
    relationshipDeclarations = unlines $
      [ "  <!-- Provenance relationships -->" | not (null sources) ] ++
      concatMap sourceRelationships sources

    -- Generate color-sample activities for pantone chip entities
    pantoneSamplingDeclarations :: String
    pantoneSamplingDeclarations = unlines $ concatMap pantoneActivityForSource sources

    pantoneActivityForSource :: SourcedElement -> [String]
    pantoneActivityForSource (name, SourceReference e)
      | "PMS" `isPrefixOf` entityTitle e =
          let key = entityTitle e
              actId = "color-sample-" ++ escId key
              sampledId = isoLower ++ "_" ++ escId name
              entId = entityIdStr e
          in [ "  <prov:activity prov:id=\"cf:" ++ actId ++ "\">"
             , "    <prov:label>color-sample " ++ escXml key ++ "</prov:label>"
             , "    <prov:type xsd:type=\"xsd:QName\">cf:color-sample</prov:type>"
             , "  </prov:activity>"
             , "  <prov:wasGeneratedBy>"
             , "    <prov:entity prov:ref=\"cf:" ++ sampledId ++ "\" />"
             , "    <prov:activity prov:ref=\"cf:" ++ actId ++ "\" />"
             , "  </prov:wasGeneratedBy>"
             , "  <prov:used>"
             , "    <prov:activity prov:ref=\"cf:" ++ actId ++ "\" />"
             , "    <prov:entity prov:ref=\"cf:" ++ entId ++ "\" />"
             , "  </prov:used>"
             , "  <prov:wasAssociatedWith>"
             , "    <prov:activity prov:ref=\"cf:" ++ actId ++ "\" />"
             , "    <prov:agent prov:ref=\"cf:pantone\" />"
             , "  </prov:wasAssociatedWith>"
             ]
    pantoneActivityForSource _ = []

    sourceRelationships :: SourcedElement -> [String]
    sourceRelationships (name, SourceReference e) =
      wasDerivedFrom name e
    sourceRelationships (name, SourceImpliedReference e) =
      wasInfluencedBy name e
    sourceRelationships (name, SourceUnsightedReference e refs) =
      wasDerivedFrom name e ++ concatMap (wasInfluencedBy name) refs
    sourceRelationships (name, SourceEditorial refs) =
      wasAttributedToEditor name ++ concatMap (wasInfluencedBy name) refs

    wasDerivedFrom :: String -> Entity -> [String]
    wasDerivedFrom name e =
      [ "  <prov:wasDerivedFrom>"
      , "    <prov:generatedEntity prov:ref=\"cf:" ++ isoLower ++ "_" ++ escId name ++ "\" />"
      , "    <prov:usedEntity prov:ref=\"cf:" ++ effectiveIdStr e ++ "\" />"
      , "  </prov:wasDerivedFrom>"
      ]

    wasInfluencedBy :: String -> Entity -> [String]
    wasInfluencedBy name e =
      [ "  <prov:wasInfluencedBy>"
      , "    <prov:influencee prov:ref=\"cf:" ++ isoLower ++ "_" ++ escId name ++ "\" />"
      , "    <prov:influencer prov:ref=\"cf:" ++ effectiveIdStr e ++ "\" />"
      , "  </prov:wasInfluencedBy>"
      ]

    wasAttributedToEditor :: String -> [String]
    wasAttributedToEditor name =
      [ "  <prov:wasAttributedTo>"
      , "    <prov:entity prov:ref=\"cf:" ++ isoLower ++ "_" ++ escId name ++ "\" />"
      , "    <prov:agent prov:ref=\"cf:editor\" />"
      , "  </prov:wasAttributedTo>"
      ]

    -- Generate a safe ID from an entity title
    entityIdStr :: Entity -> String
    entityIdStr e = escId (entityTitle e)

    -- ID for the screenshot of an entity
    screenshotIdStr :: Entity -> String
    screenshotIdStr e = "screenshot_" ++ entityIdStr e

    -- ID for the translation of an entity
    translationIdStr :: Entity -> String
    translationIdStr e = "translation_" ++ entityIdStr e

    -- Effective ID: translation > screenshot > entity (outermost in chain)
    effectiveIdStr :: Entity -> String
    effectiveIdStr e = case entityTranslated e of
      Just _  -> translationIdStr e
      Nothing -> case entityScreenshot e of
        Just _  -> screenshotIdStr e
        Nothing -> entityIdStr e

    -- Escape a string for use as an XML ID (replace spaces/special chars with underscores)
    escId :: String -> String
    escId = map (\c -> if c `elem` validIdChars then c else '_')
      where validIdChars = ['a'..'z'] ++ ['A'..'Z'] ++ ['0'..'9'] ++ "_-."

    -- Escape special XML characters
    escXml :: String -> String
    escXml = concatMap escChar
      where
        escChar '<' = "&lt;"
        escChar '>' = "&gt;"
        escChar '&' = "&amp;"
        escChar '"' = "&quot;"
        escChar '\'' = "&apos;"
        escChar c   = [c]
